### ISSUE TITLE
forge BSgenome data package from unpublished genome

### ISSUE THREAD

**Issue by tamaraprieto** [Bioconductor/BSgenome#11]
Thanks for the vignette on how to forge a BSgenome data package!It is so useful. I would like to create a package for a still unpublished genome I have access to, and I was wondering if it is possible to do it with missing fields as `source_url` or `release_date` for instance. I had already created the twoBit file and a seed file without some fields and I am getting the following error (it seems has nothing to do with the missing fields but I am uncertain) when running `forgeBSgenomeDataPkg`
```
Error in forgeBSgenomeDataPkg(y, seqs_srcdir = seqs_srcdir, destdir = destdir,  :
  values for symbols PKGVERSION are not single strings
```
Could you please help me?Thanks in advance!

**Comment by hpages** [comment]
Hi,

This error seems to indicate that your seed file is lacking the `Version` field.

Can't remember whether the `source_url` or `release_date` fields are mandatory or not. However these fields are informative only and not used for anything so you can always try to set them to `NA` or something like that.

H.

**Comment by tamaraprieto** [comment]
Thank you!I did not realize I was missing `Version`. I was able to build the package by setting the missing fields to `pending`
