### ISSUE TITLE
Load a genome - Chlamydomonas reinhardtii v5 genome

### ISSUE THREAD

**Issue by mullerbsf** [Bioconductor/BSgenome#12]
Dear,

I am trying to run the MutationalPatterns and load the Chlamydomonas reinhardtii v5 genome using BSgenome. However, it is not available in the BSgenome library.

I tried to install and load a new genome there. But I had some issues and I was not able to figure it out quickly. Could you please help me with that? How can I load a new genome using the FASTA file? If possible, could you please install it for me?

The genome (Creinhardtii_281_v5.0.fa) was download from Phytozome: https://phytozome.jgi.doe.gov/pz/portal.html#!info?alias=Org_Creinhardtii

It will be the most benefit of having this reference genome uniform across multiple packages on Bioconductor.

I really appreciate your help!

Best regards,
Barbara.

**Comment by mullerbsf** [comment]
Dear @hpages 

Could you please help me with the request above?

Thank you!
Barbara.

**Comment by mullerbsf** [comment]
Dear @LiNk-NY, 

I opened this request almost 30 days ago. Could you please direct someone who could help with this?

Thank you!
Barbara.

**Comment by hpages** [comment]
Hi @mullerbsf ,

Sorry for missing this. I can try to make that BSgenome package for you. Is it OK if I use this assembly instead? https://www.ncbi.nlm.nih.gov/assembly/GCA_000002595.3

I don't seem to have access to the `Creinhardtii_281_v5.0.fa` file at the link you provided above. The assembly available at NCBI is v5.5 so seems a little bit more recent than `Creinhardtii_281_v5.0.fa`.

H.

**Comment by mullerbsf** [comment]
Dear @hpages,

I need to verify if this is the same that I used to generate all my VCF files. On Phytozome, you should be able to download, but it just required a login first, then go to "bulk data".

I would prefer it if I can send my FASTA file (Creinhardtii_281_v5.0_mod_VCF.fa) to you because I renamed the chromosomes provided from the original (Creinhardtii_281_v5.0.fa) Phytozome. 
How can I transfer my file to you? It has only 31.6 Mb the .gz file.

Thank you very much for your help.

Best regards,
Barbara.

**Comment by mullerbsf** [comment]
Dear @hpages  ,

I would prefere if I can send my fasta file (Creinhardtii_281_v5.0_mod_VCF.fa) to you, because I renamed the chromosomes provided from the original (Creinhardtii_281_v5.0.fa) Phytozome. 
How can I transfer my file to you? It has only 31.6 Mb the .gz file.

Thanks!
Barbara.

**Comment by LiNk-NY** [comment]
Hi Barbara, @mullerbsf

We'd prefer to use data from a public resource such as the one Hervé linked to make sure that it is openly available. 
Are there any restrictions on the redistribution of the 5.0 file?
Thanks.

**Comment by mullerbsf** [comment]
Dear @hpages and @LiNk-NY,

Are you able to download the version v5.6 of Phytozome? It is public and free, but JGI just requires login first.
Then, you will be able to download the file: Creinhardtii_281_v5.0.fa.gz under v.5.6 assembly.

Let me know if you will be able to make it available in the BSgenome.

Thank you very much for it.
Barbara.

**Comment by hpages** [comment]
I was able to download `Creinhardtii_281_v5.0.fa.gz` under v.5.6 assembly. I'm looking at the file now, comparing it with the assembly at NCBI.

**Comment by hpages** [comment]
It was brought to my attention that it's not clear that the licence for this file is actually compatible with the redistribution as a publicly available BSgenome package. So I'm investigating 2 alternate solutions:
1. Based on my preliminary comparison of `Creinhardtii_281_v5.0.fa.gz` with the assembly publicly available at NCBI, it seems that the differences between the 2 assemblies are minor e.g. some regions (e.g. `chromosome_2:3129927-9223677`) are masked in the latter but not in the former. Since this kind of difference doesn't alter the coordinate system, which is crucial if you work with VCF files, this would make the NCBI assembly a decent substitute for `Creinhardtii_281_v5.0.fa.gz` .
2. If 1. doesn't work, I'll write down here the detailed instructions that help you forge your own BSgenome data package using `Creinhardtii_281_v5.0.fa.gz`. This package will be for your own private use so _we_ (the Bioconductor team) will stay clear from any license violation.

**Comment by mullerbsf** [comment]
The assembly on Phytozome is public. It is just a JGI database for plants:

"The data on the next page is public, please cite the following:
Merchant SS, Prochnik SE, et al., The Chlamydomonas genome reveals the evolution of key animal and plant functions., Science (New York, N.Y.). 2007 Oct 12; 318 5848 245-50"

I believe it does not exist a problem in using the Creinhardtii_281_v5.0.fa.gz file.

I noted the most difference between the two assemblies are the masked regions in the entire genome. The scaffolds also look different from the NCBI database. The region in chromosome 2 will be fundamental in my study, we have several SNPs and mutations there to report.

Thank you!
Barbara.

**Comment by hpages** [comment]
Barbara,

**BSgenome.Creinhardtii.JGI.v5.6** will become available via `BiocManager::install()` in the next couple hours. After you install and load the package, see `citation("BSgenome.Creinhardtii.JGI.v5.6")` for how to cite the data.

Cheers,
H.

**Comment by lshep** [comment]
I can confirm this is now available with `BiocManager::install("BSgenome.Creinhardtii.JGI.v5.6")` .

**Comment by mullerbsf** [comment]
Does it do not work for R 4.0?

> BiocManager::install("BSgenome.Creinhardtii.JGI.v5.6")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.0 (2020-04-24)
Installing package(s) 'BSgenome.Creinhardtii.JGI.v5.6'
Warning message:
package ‘BSgenome.Creinhardtii.JGI.v5.6’ is not available (for R version 4.0.0)

**Comment by lshep** [comment]
We do not update old versions of Bioconductor.  Release 3.11 is frozen.  You should update to use Bioconductor 3.12 and it will be available.  Bioconductor 3.12 also works with R 4.0.

**Comment by LiNk-NY** [comment]
This worked for me on Bioconductor 3.12. Thanks!

```r
> BiocManager::install("BSgenome.Creinhardtii.JGI.v5.6")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 Patched (2020-10-13
  r79342)
Installing package(s) 'BSgenome.Creinhardtii.JGI.v5.6'
trying URL 'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/BSgenome.Creinhardtii.JGI.v5.6_1.5.0.tar.gz'
Content type 'application/x-gzip' length 25135793 bytes (24.0 MB)
==================================================
downloaded 24.0 MB

* installing *source* package 'BSgenome.Creinhardtii.JGI.v5.6' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (BSgenome.Creinhardtii.JGI.v5.6)
```

**Comment by mullerbsf** [comment]
It worked for me too on Bioconductor 3.12.

I really appreciate all the help here!

Best regards, 
Barbara.
