### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by max1c** [Bioconductor/BSgenome#15]
Bioconductor.org says that 1.58.0 is the latest version of the package: https://bioconductor.org/packages/release/bioc/html/BSgenome.html

However, when I run BiocManager::install("BSgenome") I get the 1.56.0. Any help with this?

**Comment by hpages** [comment]
Maybe that's because you're running an old Bioconductor version. What's your `sessionInfo()`?

Latest BSgenome (1.58.0) is intended for latest Bioconductor release (BioC 3.12), which requires R 4.0.

**Comment by max1c** [comment]
You are correct, Updating biocmanger to the latest version fixed the problem. Thanks!
