### ISSUE TITLE
Forging BSgenome that is not registered

### ISSUE THREAD

**Issue by alutservitz** [Bioconductor/BSgenome#16]
Hi! I think I may be missing something basic when forging a BSgenome that is not registered with NCBI.

Here is the error I receive:
```
> library(BSgenome)
> forgeBSgenomeDataPkg("/Users/alyssa/Desktop/genome/BSgenome.Cjacchus.NCBI.cj1700.1.1-seed")
Error in .make_Seqinfo_from_genome(genome) : 
  "Callithrix_jacchus_cj1700_1.1" is not a registered NCBI assembly or UCSC genome (use registered_NCBI_assemblies() or
  registered_UCSC_genomes() to list the NCBI or UCSC assemblies/genomes currently registered in the GenomeInfoDb
  package)
```

Here is my seed file:
```
Package: BSgenome.Cjacchus.NCBI.cj1700.1.1
Title: Full genome sequence for Callithrix jacchus (cj1700_1.1)
Description: Full genome sequence for Callithrix jacchus provided by NCBI (assembly accession GCA_009663435.2) and stored in Biostrings objects.
Version: 1.0.0
organism: Callithrix jacchus
common_name: White-tufted-ear marmoset
genome: Callithrix_jacchus_cj1700_1.1
provider: NCBI
release_date: 2020-05-22
source_url: https://www.ncbi.nlm.nih.gov/assembly/GCA_009663435.2
organism_biocview: Callithrix_jacchus
BSgenomeObjname: cj1700
seqs_srcdir: /Users/alyssa/Desktop/genome
seqfile_name: cj1700.2bit
```

When I include 'circ_seqs: character(0)' in my seed file the error goes away and it will run (very quickly), 
```
> forgeBSgenomeDataPkg("/Users/alyssa/Desktop/genome/BSgenome.Cjacchus.NCBI.cj1700.1.1-seed")
Creating package in ./BSgenome.Cjacchus.NCBI.cj1700.1.1 
Copying '/Users/alyssa/Desktop/genome/cj1700.2bit' to './BSgenome.Cjacchus.NCBI.cj1700.1.1/inst/extdata/single_sequences.2bit' ... DONE
```
but it doesn't appear to build correctly. Am I doing something wrong in my seed file, or do you see any other mistakes that I may be making?

**Comment by wmdai988** [comment]
I met the same problem as yours. Do you find the solution? Thanks!

**Comment by alutservitz** [comment]
@dmaibao yes I did! Looks like you need to include 'circ_seqs: character(0)' if using a .2bit file. My issue was that I was running the build command in the wrong place (silly mistake). Were you able to to find a solution? If not, I'd be happy to help.

**Comment by hpages** [comment]
Sorry for missing this.

A few comments:

1. The Callithrix_jacchus_cj1700_1.1 assembly includes the MT sequence which is circular.

2. I've registered Callithrix_jacchus_cj1700_1.1 (as well as a few additional Callithrix jacchus NCBI assemblies) in the latest **GenomeInfoDb** (version 1.26.3, it will become available via `BiocManager::install()` in the next 48 hours). With this new version you can do:
    ```
    library(GenomeInfoDb)
    
    si <- Seqinfo(genome="Callithrix_jacchus_cj1700_1.1")
    si
    # Seqinfo object with 964 sequences (1 circular) from Callithrix_jacchus_cj1700_1.1 genome:
    #   seqnames              seqlengths isCircular                        genome
    #   chr1                   217961735      FALSE Callithrix_jacchus_cj1700_1.1
    #   chr2                   204486479      FALSE Callithrix_jacchus_cj1700_1.1
    #   chr3                   191910223      FALSE Callithrix_jacchus_cj1700_1.1
    #   chr4                   174041770      FALSE Callithrix_jacchus_cj1700_1.1
    #   chr5                   164351765      FALSE Callithrix_jacchus_cj1700_1.1
    #   ...                          ...        ...                           ...
    #   chrUn_000472F_qpd_obj     122224      FALSE Callithrix_jacchus_cj1700_1.1
    #   chrUn_001100F_qpd_obj      16639      FALSE Callithrix_jacchus_cj1700_1.1
    #   chrUn_000802F_qpd_obj      49468      FALSE Callithrix_jacchus_cj1700_1.1
    #   chrUn_000527F_qpd_obj     128105      FALSE Callithrix_jacchus_cj1700_1.1
    #   chrUn_000807F_qpd_obj      47798      FALSE Callithrix_jacchus_cj1700_1.1
    
    isCircular(si)[1:25]
    #  chr1  chr2  chr3  chr4  chr5  chr6  chr7  chr8  chr9 chr10 chr11 chr12 chr13 
    # FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE 
    # chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22  chrX  chrY    MT 
    # FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE 
    ```

3. Forging a BSgenome for an NCBI assembly usually involves a little bit more work than for an UCSC genome. Typically it requires converting the FASTA file provided by NCBI (`_genomic.fna.gz`) to the 2bit format. This can easily be done using standard Bioconductor tools. For example, for the `BSgenome.Gmellonella.NCBI.ASM364042v2` package, I used [the following script](https://github.com/Bioconductor/BSgenome/tree/master/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-tools) to convert the `GCF_003640425.2_ASM364042v2_genomic.fna.gz` file to the 2bit format. Then preparing a seed file that works with this 2bit file should be pretty straightforward. See for example the [seed file](https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-seed) I used for Gmellonella. It should be easy to adapt.

Hope this helps,

H.
