### ISSUE TITLE
forge custom BSgenome error: not a registered NCBI assembly or UCSC genome

### ISSUE THREAD

**Issue by santataRU** [Bioconductor/BSgenome#20]
Dear BSgenome developer,

I have one error during my forge of custom BSgenome package, my seed file is below:

**Package: BSgenome.NL43.Xiao.NL43_CLIP
Title: Full genome sequences for NL43
Description: NL43
Version: 1.0.0
organism: HIV
common_name:HIV
provider: Xiao
genome:NL43
release_date: Sep. 2021
source_url:/Users/xiaolei/Desktop/seqs_srcdir/NL43.2bit
organism_biocview: NL43
BSgenomeObjname: NL43
seqs_srcdir: /Users/xiaolei/Desktop/seqs_srcdir
seqfile_name:NL43.2bit**

After I run: `forgeBSgenomeDataPkg("/Users/xiaolei/Desktop/seqs_srcdir/NL43_seed.dcf.txt")`.  I had an error message:

**Error in .make_Seqinfo_from_genome(genome) : 
  "NL43" is not a registered NCBI assembly or UCSC genome (use
  registered_NCBI_assemblies() or registered_UCSC_genomes() to list the NCBI or UCSC
  assemblies/genomes currently registered in the GenomeInfoDb package)**

I can circumvent this problem by changing the genome name to "ViralProj15500", which is a registered genome.  I do not want to do this because my genome is a custom genome based on HIV viruses (not NCBI, nor UCSC registered genome). 

Why users could not put any name they want in the "genome" field? Is there a way to do so?

Regards,

Xiao

**Comment by hpages** [comment]
You can put whatever name you want in the `genome` field. It's just that if the genome is registered in **GenomeInfoDb**, then you don't need to specify the `seqnames` field because, in this case, `forgeBSgenomeDataPkg()` will be able to fetch the sequence names for you. However if the genome is _not_ registered, then you _must_ specify the `seqnames` field.

So the process of forging a BSgenome data package is just more convenient when the genome is registered in **GenomeInfoDb**, but it's not a requirement.

Best,
H.

**Comment by santataRU** [comment]
Thanks Hervé. I can build the BSgenome package without problem, but I have an error after I check the package with `R CMD check <tarball>`. The error message is below:

**using log directory ‘/Users/bieniaszlab/Desktop/seqs_srcdir/BSgenome.NL43.Xiao.NL43CLIP/BSgenome.NL43.Xiao.NL43CLIP.Rcheck’
* using R version 4.0.2 (2020-06-22)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘BSgenome.NL43.Xiao.NL43CLIP/DESCRIPTION’ ... OK
* this is package ‘BSgenome.NL43.Xiao.NL43CLIP’ version ‘0.1’
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Package required and available but unsuitable version: ‘BSgenome’

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE
Status: 1 ERROR**

Do I have to add 'BSgenome' dependencies in my package?  If yes what should I do?

Regards,

Xiao

**Comment by LiNk-NY** [comment]
Hi Xiao, @santataRU 
Make sure that `BiocManager::valid()` returns TRUE. 
Bioc-devel is currently using R version 4.1. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
Should the error message say that the `seqnames` must be specified?

**Comment by santataRU** [comment]
Hi, Marcel,

Thanks for your help. I actually did not include "seqnames", instead, I include "circ_seqs: character(0)" in my seed file. The seed file works well.

Best,
Xiao

**Comment by santataRU** [comment]
Dear BSgenome developers,

Although I can forge the BSgeome (RREWT_CLIP), install and load in Rstudio without a problem. I have the following error during my run of wavClusteR: 

require(BSgenome.NL43.Xiao.RREWT)

wavclusters <- filterClusters( clusters = clusters, 
                               highConfSub = highConfSub,
                               coverage = coverage, 
                               model = model, 
                               genome = RREWT_CLIP, 
                               refBase = "T", 
                               minWidth = 12)
**Error in .getOneSeqFromBSgenomeMultipleSequences(x, names[i], start[i],  : 
  sequence RREWT_CLIP not found**

I appreciate if you have any inputs about it. This may be a problem of the wavClusteR package though, if not a BSgenome problem. I attach my seed file content at the end. 

Regards,

Xiao

Seed file content:
Package: BSgenome.NL43.Xiao.RREWT
Title: RREWT CLIP alignment sequences
Description: RREWT_CLIP_9179bp
Version: 0.1
Author:Xiao
Maintainer:Xiao Lei <xxx@gmail.com>
organism: HIV
common_name:RREWT_CLIP
provider:Xiao
genome:RREWT_CLIP
release_date: Sep. 2021
source_url:~/Desktop/seqs_srcdir/RREWT.2bit
organism_biocview: NL43
BSgenomeObjname: RREWT_CLIP
circ_seqs: character(0)
seqs_srcdir: ~/Desktop/seqs_srcdir
seqfile_name:RREWT.2bit

**Comment by LiNk-NY** [comment]
Hi Xiao, @santataRU 

Please file an issue for the `wavClusteR` package or go to the https://support.bioconductor.org/ and ask for help there from the maintainers.

Be sure to provide an entirely reproducible example. 
See here for more details: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Best,
Marcel

**Comment by santataRU** [comment]
Hi, Marcel,

Thank you. I already contacted the author of wavClusteR. I am waiting for his reply.

Best,

Xiao

**Comment by hpages** [comment]
hmm... something does not look right with your **BSgenome.NL43.Xiao.RREWT** package. What do you get when you do:
```
library(BSgenome.NL43.Xiao.RREWT)

BSgenome.NL43.Xiao.RREWT

seqinfo(BSgenome.NL43.Xiao.RREWT)
```
Also can you manually load some of the sequences listed in the output produced by the above?

**Comment by santataRU** [comment]
Dear Hervé, 

Thank you very much for your help. I pasted below the output:

> `library(BSgenome.NL43.Xiao.RREWT)`
> `BSgenome.NL43.Xiao.RREWT`
RREWT_CLIP genome:
#organism: HIV (RREWT_CLIP)
#genome: RREWT_CLIP
#provider: Xiao
#release date: Sep. 2021
#1 sequences:
#RREWT_CLIP                                                                             
#(use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator to access a given sequence)
> `seqinfo(BSgenome.NL43.Xiao.RREWT)`
Seqinfo object with 1 sequence from RREWT_CLIP genome:
  seqnames   seqlengths isCircular     genome
  RREWT_CLIP       9179      FALSE RREWT_CLIP

However, I got error if I run the command `seqnames()`, the error is below:
 **`seqnames()`
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"missing"’**

Is there something wrong with my package? 

If I want to see the sequence of my genome, what command should I use in Rstudio to show the genome sequence of my custom build BSgenome?

Thanks again,

X

**Comment by santataRU** [comment]
Dear Hervé, 

I modified my seed file (attached to the end). Make sure part 2 of the package name matched to BSgenomeObjname and the sequence name of my fasta file (RREWTCLIP). I indexed the fasta file and aligned this genome with reads with Bowtie alignment tool. wavClusteR could read my BSgenome this time, but still output an error (error solving row 1: the supplied start/end lead to a negative width), this may be due to wavClusteR or due to problems from BSgenome I forged.

Thanks,

Xiao

```
 wavclusters <- filterClusters( clusters = clusters, 
                               highConfSub = highConfSub,
                               coverage = coverage, 
                               model = model, 
                               genome = RREWTCLIP, 
                               refBase = "T", 
                               minWidth = 12)
```
Computing log odds...
Refining cluster sizes...
Combining clusters...
Quantifying transitions within clusters...
Computing statistics...
**Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : solving row 1: the supplied start/end lead to a negative width**


My seed file:

Package: BSgenome.RREWTCLIP.Xiao.NL43
Title: RREWT CLIP alignment sequences
Description: RREWT_CLIP_9179bp
Version: 0.1
Author:Xiao
Maintainer:Xiao Lei <xxx@gmail.com>
organism: HIV
common_name:RREWTCLIP
provider:Xiao
genome:RREWTCLIP
release_date: Sep. 2021
source_url:~/Desktop/seqs_srcdir/RREWT.2bit
organism_biocview: NL43
BSgenomeObjname: RREWTCLIP
circ_seqs: character(0)
seqs_srcdir: ~/Desktop/seqs_srcdir
seqfile_name:RREWT.2bit

**Comment by hpages** [comment]
`seqnames()` is an accessor function to extract the sequence names from the BSgenome object. You need to call it on the object:
```
seqnames(BSgenome.NL43.Xiao.RREWT)
```
Then try this:
```
BSgenome.NL43.Xiao.RREWT[["RREWT_CLIP"]]
```
This should return the `RREWT_CLIP` sequence in a DNAString object.

Does it work?

H.

**Comment by santataRU** [comment]
Thanks for your help. I can get a partial sequence from `getSeq(RREWTCLIP, end=10)`, but I got an error if I tried to retrieve full sequences from `BSgenome.RREWTCLIP.Xiao.NL43[["RRREWTCLIP"]]` (by the way I forged a BSgenome with seqnames of "RREWTCLIP"). 

Below are my results:

```
 library(BSgenome.RREWTCLIP.Xiao.NL43)
 seqnames(BSgenome.RREWTCLIP.Xiao.NL43)
```
[1] "RREWTCLIP"

`BSgenome.RREWTCLIP.Xiao.NL43[["RRREWTCLIP"]]`

**Error in BSgenome.RREWTCLIP.Xiao.NL43[["RRREWTCLIP"]] : no such sequence**

`getSeq(RREWTCLIP, end=10)`
10-letter DNAString object
seq: GGTCTCTCTG

My seed file is below:

Package: BSgenome.RREWTCLIP.Xiao.NL43
Title: RREWT CLIP alignment sequences
Description: RREWT_CLIP_9179bp
Version: 0.1
Author:Xiao
Maintainer:Xiao Lei <xxx@gmail.com>
organism: HIV
common_name:RREWTCLIP
provider:Xiao
genome:RREWTCLIP
release_date: Sep. 2021
source_url:~/Desktop/seqs_srcdir/RREWT.2bit
organism_biocview: NL43
BSgenomeObjname: RREWTCLIP
circ_seqs: character(0)
seqs_srcdir: ~/Desktop/seqs_srcdir
seqfile_name:RREWT.2bit


Thanks.

X

**Comment by hpages** [comment]
That's because the name of the sequence is `RREWTCLIP` (only 2 `R`'s), not `RRREWTCLIP`.

**Comment by santataRU** [comment]
> That's because the name of the sequence is `RREWTCLIP` (only 2 `R`'s), not `RRREWTCLIP`.
Dear Hervé,
I see. Thank you very much!
