### ISSUE TITLE
Error: values for symbols PKGVERSION are not single strings

### ISSUE THREAD

**Issue by gevro** [Bioconductor/BSgenome#23]
Hi, I'm getting this error:
```
Error in forgeBSgenomeDataPkg(y, seqs_srcdir = seqs_srcdir, destdir = destdir,  : 
  values for symbols PKGVERSION are not single strings
```

Seed file:
```
Package: BSgenome.Hsapiens.T2T.CHM13v1
Title: T2T CHM13 v1.0
Description: Full genome sequence for T2T CHM13 v1.0
organism: Homo sapiens
common_name: H. Sapiens
genome: CHM13v1
provider: T2T
release_date: 2021/11
source_url: https://github.com/marbl/CHM13
organism_biocview: Homo_sapiens
BSgenomeObjname: Hsapiens
seqs_srcdir: /Users/giladevrony/Downloads/chm13/seqs_srcdir
seqfile_name: chm13.draft_v1.0.2bit
circ_seqs: ""

```

**Comment by gevro** [comment]
I think I found the problem, I'm missing the 'Version' field.

**Comment by hpages** [comment]
Yes, 2 problems:
1. `Version` is a mandatory field.
2. `circ_seqs` should be `character(0)`, not `""`. The latter means that there is one circular sequence and that its name is the empty string.

Please refer to the BSgenomeForge.Rnw vignette and make sure to carefully follow the instructions.

Thanks!

**Comment by hpages** [comment]
@gevro FYI we've wrapped the T2T-CHM13 assembly in a new BSgenome data package: https://bioconductor.org/packages/BSgenome.Hsapiens.NCBI.T2T.CHM13v2.0

Available in BioC >= 3.15 only.

Best,
H.

**Comment by gevro** [comment]
Thanks! Might be useful to also have 1.0 and 1.1, since some people use that, but just a suggestion.

**Comment by hpages** [comment]
1.0 and 1.1 are incomplete (Y is missing) and not supported by UCSC (https://genome.ucsc.edu/h/GCA_009914755.4) so have little value compared to 2.0. I've registered them in **GenomeInfoDb** 1.31.8 though:
```
> library(GenomeInfoDb)
> subset(registered_NCBI_assemblies()[c("organism", "assembly")], organism == "Homo sapiens")
        organism      assembly
109 Homo sapiens        NCBI33
110 Homo sapiens        NCBI34
111 Homo sapiens        NCBI35
112 Homo sapiens        NCBI36
113 Homo sapiens        GRCh37
114 Homo sapiens    GRCh37.p13
115 Homo sapiens        GRCh38
116 Homo sapiens     GRCh38.p1
117 Homo sapiens     GRCh38.p2
118 Homo sapiens     GRCh38.p3
119 Homo sapiens     GRCh38.p4
120 Homo sapiens     GRCh38.p5
121 Homo sapiens     GRCh38.p6
122 Homo sapiens     GRCh38.p7
123 Homo sapiens     GRCh38.p8
124 Homo sapiens     GRCh38.p9
125 Homo sapiens    GRCh38.p10
126 Homo sapiens    GRCh38.p11
127 Homo sapiens    GRCh38.p12
128 Homo sapiens    GRCh38.p13
129 Homo sapiens    GRCh38.p14
130 Homo sapiens T2T-CHM13v0.7
131 Homo sapiens T2T-CHM13v1.0
132 Homo sapiens T2T-CHM13v1.1
133 Homo sapiens T2T-CHM13v2.0
```
So people can do things like `getChromInfoFromNCBI("T2T-CHM13v1.1")` or `Seqinfo(genome="T2T-CHM13v0.7")`. This should also make it easy for them to build their own BSgenome data packages for those assemblies if they wish so.

H.
