### ISSUE TITLE
BSgenome package not available

### ISSUE THREAD

**Issue by prmunn** [Bioconductor/BSgenome#30]
I've run through the vignette to forge a new genome. I can build the package using R CMD build <package directory> and create the tar file. However, when I run R CMD check I get a message saying "Package required but not available: BSgenome"

Similarly, when I attempt to install I get the message:
ERROR: dependency BSgenome is not available for package BSgenome.Equuscabellus.UCSC.equCab3

What do I need to get these commands working?

**Comment by hpages** [comment]
Install the **BSgenome** package:

    BiocManager::install("BSgenome")

Not sure how it's missing though. You wouldn't have been able to forge **BSgenome.Equuscabellus.UCSC.equCab3** without it.

**Comment by prmunn** [comment]
Ah... I see where I went wrong. I loaded BSgenome into Rstudio in order to forge the genome. I need to run R from the command line and load the library there before "R CMD" can use it.
