### ISSUE TITLE
Malformed package name

### ISSUE THREAD

**Issue by m-waqas** [Bioconductor/BSgenome#33]
Hi, I am trying to forge the genome of [Pteropus alecto ](https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000325575.1/), I have downloaded the [zipped genome fasta file ](https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9402/102/GCF_000325575.1_ASM32557v1/GCF_000325575.1_ASM32557v1_genomic.fna.gz), converted the fasta file into 2bit using [fasta_to_sorted_2bit.R](https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-tools/fasta_to_sorted_2bit.R). Next I have generated the seed file by following the [format](https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-seed). Content of seed file is as follows:

```
Package: BSgenome.P_alecto_v1a
Title: Full genome sequence for P alecto
Description: Full genome sequences of Pteropus alecto as provided by NCBI assembly ASM32557v1, assembly accession GCF_000325575.1) and stored in Biostrings objects
Version: 1.0
organism: Pteropus alecto
common_name: Black flying fox
genome: ASM32557v1
provider: NCBI
release_date: 201304
source_url: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000325575.1
organism_biocview: Pteropus_alecto
BSgenomeObjname: Palecto
circ_seqs: "NC_023122.1"
SrcDataFiles: GCF_000325575.1_ASM32557v1_genomic.fna.gz from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/325/575/GCF_000325575.1_ASM32557v1/
PkgExamples: genome[["NC_023122.1"]]
seqs_srcdir: /home/super/Documents/Bat_expression_analysis/BS_genome_p_alecto/src_seqdir
seqfile_name: P_alecto_new.2bit
```
Forging: 
```
> forgeBSgenomeDataPkg("BSgenome.P_alecto")
Creating package in ./BSgenome.P_alecto_v1a 
Copying '/home/super/Documents/Bat_expression_analysis/BS_genome_p_alecto/src_seqdir/P_alecto_new.2bit' to './BSgenome.P_alecto_v1a/inst/extdata/single_sequences.2bit' ... DONE
```

It forged successfully but I get an error once  I try to build:

` super@super-ThinkPad-P17-Gen-1:~/Documents/Bat_expression_analysis/BS_genome_p_alecto/src_seqdir$ R CMD build BSgenome.P_alecto_v1a`

```
WARNING: ignoring environment value of R_HOME
* checking for file ‘BSgenome.P_alecto_v1a/DESCRIPTION’ ... OK
* preparing ‘BSgenome.P_alecto_v1a’:
* checking DESCRIPTION meta-information ... ERROR
Malformed package name

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
```

I am unsure where I am making a mistake, Any help will be highly appreciated.

I want to use the BSgenome in [IsoformSwitchAnalyzeR](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#installation), Is it possible to use BSgenome without building it?

**Comment by hpages** [comment]
Well, it says that the name of your package is malformed so here's where you're making a mistake.

For the general rules about naming an R package see section "1.1.1 The DESCRIPTION file" of the ["Writing R Extensions manual"](https://cran.r-project.org/doc/manuals/r-release/R-exts.html). The TL;DR version is that underscores (`_`) are not allowed.
 
FURTHERMORE: For the specific naming conventions that you should follow when naming a BSgenome data package, see the "How to forge a BSgenome data package" vignette in the [**BSgenome** package](https://bioconductor.org/packages/BSgenome). Hint: The package name must have at least 4 parts separated with dots (`.`) e.g. **BSgenome.Gmax.NCBI.Gmv40**. There's also a convention to follow for _each part_ of the name.

> I want to use the BSgenome in IsoformSwitchAnalyzeR, Is it possible to use BSgenome without building it?

That's something that you would need to ask to the **IsoformSwitchAnalyzeR**'s folks.

In the future please ask this kind of question on the [Bioconductor support site](https://support.bioconductor.org/). GitHub issues should preferably be used for reporting bugs or request new features.

Thanks,
H.

**Comment by hpages** [comment]
Hi @m-waqas,

Was the above helpful? Is it ok to close?

Thanks,
H.

**Comment by m-waqas** [comment]
Many thanks, Yes it was very helpful and it worked. Many thanks

**Comment by hpages** [comment]
Great! Closing now.
