### ISSUE TITLE
no existing definition for function ‘releaseName’

### ISSUE THREAD

**Issue by jeroen** [Bioconductor/BSgenome#34]
Trying to build from source on R 4.2.1 gives me:

```
2022-08-23T12:10:30.2228071Z * installing *source* package ‘BSgenome’ ...
2022-08-23T12:10:30.2229208Z ** using staged installation
2022-08-23T12:10:30.2446030Z ** R
2022-08-23T12:10:30.2788105Z ** inst
2022-08-23T12:10:30.3046263Z ** byte-compile and prepare package for lazy loading
2022-08-23T12:10:39.0182130Z Error in setMethod("releaseName", "SNPlocs", function(x) x@release_name) : 
2022-08-23T12:10:39.0183385Z   no existing definition for function ‘releaseName’
```

**Comment by vjcitn** [comment]
is BiocManager::valid() yielding TRUE?  This is for Bioconductor 3.15?

**Comment by jeroen** [comment]
Yes it is using the BioC 3.15 repo. It happens when `BSgenome` is installed as a dependency of another R package, for example [here](https://github.com/r-universe/bioconductor/commit/9557aaf382eece5b85f321909d48d61beffa8f9d/checks/7972566521/logs).

We just use `install.packages()` instead of BiocManager, but that should still work I think?

**Comment by vjcitn** [comment]
I am trying to reproduce.  It will take a few minutes as my installation is out of date.

**Comment by mtmorgan** [comment]
I see 
```
2022-08-23T11:57:07.0266118Z trying URL 'https://bioconductor.r-universe.dev/src/contrib/GenomeInfoDb_1.33.5.tar.gz'
```
where the odd 'y' in the version (33) indicates that it is the devel (master) branch, whereas in
```
2022-08-23T11:57:22.8787179Z trying URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/BSgenome_1.64.0.tar.gz'
```
the even y (64) indicates the release (Bioconductor version 3.15) branch. I also [see](https://code.bioconductor.org/browse/BSgenome/commit/3e6a7aae492496c70144da5cd27790917ae3a7f6) that `releaseName` has been removed from devel, or rather, removed from GenomeInfoDb, with a generic added in BSgenome (not quite clear how this is consistent with the commit message...)

So the problem is that your installation mixes release and devel packages.

The reason is I guess because in R (and as used by `install.packages()`, by default) we have

```
> tools:::.BioC_version_associated_with_R_version()
[1] '3.15'
```
During this release, when both Bioc devel and 3.15 are using the same version of R, this has to be the case -- point the user of `install.packages()` to the release version of Bioconductor. For the correct repositories, see
```
BiocManager::repositories(version = "devel")
```

Using `BiocManager::install()` instead of `install.packages()` would always install consistent versions of Bioconductor packages, as well as the current version of CRAN packages (it delegates CRAN packages to `install.packages()`).

Also, for what it's worth, using BiocManager on the [Bioconductor docker container](https://bioconductor.org/help/docker/), which extends a rocker container, will install binary CRAN (from RStudio) and Bioconductor (our own builds) packages.

**Comment by vjcitn** [comment]
Working from the RELEASE_3_15 branch I have
```
> pkgbuild::build()
✔  checking for file ‘/home/stvjc/BIOC_SOURCES/BSgenome/DESCRIPTION’ ...
─  preparing ‘BSgenome’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (1m 7.5s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘BSgenome/inst/pkgtemplates/BSgenome_datapkg/inst/extdata’
   Removed empty directory ‘BSgenome/inst/pkgtemplates/BSgenome_datapkg/inst’
   Removed empty directory ‘BSgenome/inst/pkgtemplates/MaskedBSgenome_datapkg/inst/extdata’
   Removed empty directory ‘BSgenome/inst/pkgtemplates/MaskedBSgenome_datapkg/inst’
─  building ‘BSgenome_1.64.0.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘BSgenome/inst/extdata/GentlemanLab/BSgenome.Gmellonella.NCBI.ASM364042v2-tools/fasta_to_sorted_2bit.R’
   
[1] "/home/stvjc/BIOC_SOURCES/BSgenome_1.64.0.tar.gz"
> sessionInfo()
R version 4.2.0 Patched (2022-05-17 r82372)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /home/stvjc/R-4-2-dist/lib/R/lib/libRblas.so
LAPACK: /home/stvjc/R-4-2-dist/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pkgbuild_1.3.1

loaded via a namespace (and not attached):
 [1] processx_3.7.0      BiocManager_1.30.18 compiler_4.2.0     
 [4] R6_2.5.1            rprojroot_2.0.3     cli_3.3.0          
 [7] prettyunits_1.1.1   tools_4.2.0         withr_2.5.0        
[10] glue_1.6.2          crayon_1.5.1        callr_3.7.2        
[13] ps_1.7.1    
```

**Comment by jeroen** [comment]
Right, r-universe is building the git checkout using the current release of R and BioC. I did not see anything in the `Depends: ` that implies the development branch of bioc is required, so I assumed it was unintentional.

**Comment by mtmorgan** [comment]
You're using the GenomeInfoDb (and other packages) from devel... The 'master' branch is always devel; releases are on RELEASE_*.

**Comment by hpages** [comment]
About the commit messages:

- Commit https://github.com/Bioconductor/GenomeInfoDb/commit/43bc04c1065f640c00f4ad4681c50558b451eff2 for **GenomeInfoDb** (from May 7):
```
...
...
- Also move the releaseName() generic function to the BSgenome package.
```
- Commit 3e6a7aae492496c70144da5cd27790917ae3a7f6 for **BSgenome** (from May 7):
```
...
...
- Also move the releaseName() generic function from the GenomeInfoDb package.
```
I wish I could make this clearer but english is not my native language ¯\\_(ツ)_/¯

Both commits were made in master at the very beginning of the 3.16 devel cycle (about 10 days after the release of BioC 3.15).

**Comment by jeroen** [comment]
OK thank you very much for the clarifications. 

I have changed the r-universe build system to build bioconductor packages under the `/bioconductor` github account from the latest release branch (e.g. `RELEASE_3_15`) instead of default git checkout. So the versions should now match those from the bioc release branch I think: https://bioconductor.r-universe.dev/ui#builds

Ideally, we would rather build everything from the latest git checkout (master branches) so we can monitor the latest commit and development activity, as we do for other R packages. However our build system runs on r-release and bioc-release, and I understand now the master branches of bioc packages are only tested to work on r-devel/bioc-devel.

**Comment by hpages** [comment]
Hi Jeroen,

Would your build system be able to grab packages from `https://git.bioconductor.org/packages/<pkgname>`?

Note that this is the primary git location for all Bioconductor packages. Only a small fraction of Bioconductor packages are actually under the `/Bioconductor` github account (basically only packages maintained by the core team). See "Source Repository" at the bottom of the package landing pages e.g. here https://bioconductor.org/packages/SingleCellExperiment

This is also where our daily builds grab packages from. See for example the _git_url_ field at https://bioconductor.org/checkResults/3.15/bioc-LATEST/SingleCellExperiment

FWIW we also maintain manifest files where we list all Bioconductor packages: `git clone https://git.bioconductor.org/admin/manifest`


Best,
H.

**Comment by hpages** [comment]
Also about this:

> and I understand now the master branches of bioc packages are only tested to work on r-devel/bioc-devel

Not really.

master branches of bioc packages are tested to work on bioc-devel + the version of R that bioc-devel is based on. This is r-devel between the Fall and Spring releases, and r-release between the Spring and Fall releases. The idea behind this scheme is that new BioC releases are always based on the latest R release.

So for example right now bioc-devel is mapped to R 4.2 and not r-devel because, when we release BioC 3.16 this Fall, r-devel won't be released as R 4.3.0 yet. After we release BioC 3.16 this Fall, bioc-devel will be based on r-devel, so when we release BioC 3.17 in Spring 2023, it will be based on the just-released R 4.3.0.

This is explained in [this document](https://contributions.bioconductor.org/use-devel.html#use-devel) which is linked from our website.

Hope this helps,
H.

**Comment by jeroen** [comment]
> Would your build system be able to grab packages from https://git.bioconductor.org/packages/<pkgname>?
> Note that this is the primary git location for all Bioconductor packages. Only a small fraction of Bioconductor packages are actually under the /Bioconductor github account (basically only packages maintained by the core team). 

Actually r-universe builds all packages that can be found on GitHub/GitLab (not just those from /bioconductor). The system has indexed almost 1000 bioc packages. You can find them via the [r-universe seach](https://r-universe.dev/search/) but I have also cross referenced them now on the bioconductor repository e.g.

 - https://bioconductor.r-universe.dev/ui#packages
 - https://bioconductor.r-universe.dev/ui#builds

The reason we prefer to build from GitHub repositories is that this provides a lot of interesting metadata about the package authors, contributors, organisation, development activity, bug tracker, and so on. It allows us to show a more comprehensive picture of the software and its developers, and cross reference other packages from the same organisation, topic, etc.

**Comment by hpages** [comment]
> The reason we prefer to build from GitHub repositories is that this provides a lot of interesting

Yeah I understand that but:
- I'm not sure there's a reliable way to find the GitHub repo that corresponds to a git repo at git.bioconductor.org, so there's no guarantee that what you find on GitHub matches what is at git.bioconductor.org
- Even when you find "the match" on GitHub, there's no guarantee that it's in sync with the git repo at git.bioconductor.org. See for example https://github.com/andrewtikhonov/ArrayExpressHTS. It's lagging years behind https://git.bioconductor.org/packages/ArrayExpressHTS ! Unfortunately this is pretty common :disappointed: 
- Some Bioconductor packages are not even on GitHub/GitLab.

**Comment by jeroen** [comment]
Thanks for your input. To clarify, we only index packages from GitHub if the official bioconductor registry mentions a Github URL in the package DESCRIPTION. So it is still up to the package author to let us know where the official GitHub source is:


```r
bioc <- jsonlite::fromJSON('https://bioconductor.org/packages/json/3.16/bioc/packages.json')
bioc$BSgenome$BugReports 
```

Your example ArrayExpressHTS is not in there, so that's why it's not on r-universe.

In General, we are mostly interested in indexing packages on r-universe that are actively maintained and could be interesting for users to discover; not such much in creating a complete bioc mirror :-)

This is getting off topic, so let's more further discussion here: https://github.com/r-universe-org/help/discussions/195
