### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by bigguscodus** [Bioconductor/BSgenome#4]
I have a problem with installation BSgenome. What am i supposed to do ? Here is the log:
> BiocManager::install("BSgenome")
Bioconductor version 3.10 (BiocManager 1.30.9), R 3.6.1 (2019-07-05)
Installing package(s) 'BSgenome'
also installing the dependencies ‘SummarizedExperiment’, ‘RCurl’, ‘XML’, ‘GenomicAlignments’, ‘Rhtslib’, ‘GenomeInfoDb’, ‘GenomicRanges’, ‘rtracklayer’, ‘Rsamtools’

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/SummarizedExperiment_1.16.0.tar.gz'
Content type 'application/x-gzip' length 1517919 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://cloud.r-project.org/src/contrib/RCurl_1.95-4.12.tar.gz'
Content type 'application/x-gzip' length 916763 bytes (895 KB)
==================================================
downloaded 895 KB

trying URL 'https://cloud.r-project.org/src/contrib/XML_3.98-1.20.tar.gz'
Content type 'application/x-gzip' length 1600829 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/GenomicAlignments_1.22.0.tar.gz'
Content type 'application/x-gzip' length 2315848 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/Rhtslib_1.18.0.tar.gz'
Content type 'application/x-gzip' length 1471164 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/GenomeInfoDb_1.22.0.tar.gz'
Content type 'application/x-gzip' length 3409309 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/GenomicRanges_1.38.0.tar.gz'
Content type 'application/x-gzip' length 1169872 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/rtracklayer_1.46.0.tar.gz'
Content type 'application/x-gzip' length 1541921 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/Rsamtools_2.2.0.tar.gz'
Content type 'application/x-gzip' length 3033552 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/BSgenome_1.54.0.tar.gz'
Content type 'application/x-gzip' length 6067030 bytes (5.8 MB)
==================================================
downloaded 5.8 MB

* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/RCurl’
* installing *source* package ‘XML’ ...
** package ‘XML’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for sed... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking for xml2-config... no
Cannot find xml2-config
ERROR: configuration failed for package ‘XML’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/XML’
* installing *source* package ‘Rhtslib’ ...
** using non-staged installation via StagedInstall field
** libs
cd "htslib-1.7" && make -f "/usr/lib/R/etc/Makeconf" -f "Makefile.Rhtslib"
make[1]: Entering directory '/tmp/Rtmpr6Dmy1/R.INSTALL4f1c631f2b98/Rhtslib/src/htslib-1.7'
Makefile.Rhtslib:128: warning: overriding recipe for target '.c.o'
/usr/lib/R/etc/Makeconf:167: warning: ignoring old recipe for target '.c.o'
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o kfunc.o kfunc.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o knetfile.o knetfile.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o kstring.o kstring.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o bgzf.o bgzf.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o errmod.o errmod.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o faidx.o faidx.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o hfile.o hfile.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.7"' > version.h
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o hts.o hts.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o hts_os.o hts_os.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o md5.o md5.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o multipart.o multipart.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o probaln.o probaln.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o realn.o realn.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o regidx.o regidx.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o sam.o sam.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o vcf_sweep.o vcf_sweep.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o tbx.o tbx.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o textutils.o textutils.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o thread_pool.o thread_pool.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o vcf.o vcf.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o vcfutils.o vcfutils.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_decode.o cram/cram_decode.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_encode.o cram/cram_encode.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_external.o cram/cram_external.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_index.o cram/cram_index.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_io.o cram/cram_io.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/cram_stats.o cram/cram_stats.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/files.o cram/files.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/mFILE.o cram/mFILE.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/rANS_static.o cram/rANS_static.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/sam_header.o cram/sam_header.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o cram/string_alloc.o cram/string_alloc.c
gcc -std=gnu99 -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -I.  -D_FILE_OFFSET_BITS=64 -c -o hfile_libcurl.o hfile_libcurl.c
hfile_libcurl.c:45:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile.Rhtslib:128: recipe for target 'hfile_libcurl.o' failed
make[1]: Leaving directory '/tmp/Rtmpr6Dmy1/R.INSTALL4f1c631f2b98/Rhtslib/src/htslib-1.7'
make[1]: *** [hfile_libcurl.o] Error 1
Makevars.common:24: recipe for target 'htslib' failed
make: *** [htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/Rhtslib’
ERROR: dependency ‘RCurl’ is not available for package ‘GenomeInfoDb’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/GenomeInfoDb’
ERROR: dependency ‘GenomeInfoDb’ is not available for package ‘GenomicRanges’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/GenomicRanges’
ERROR: dependencies ‘GenomicRanges’, ‘GenomeInfoDb’ are not available for package ‘SummarizedExperiment’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/SummarizedExperiment’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘Rhtslib’ are not available for package ‘Rsamtools’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/Rsamtools’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘Rsamtools’ are not available for package ‘GenomicAlignments’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/GenomicAlignments’
ERROR: dependencies ‘GenomicRanges’, ‘XML’, ‘GenomeInfoDb’, ‘RCurl’, ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/rtracklayer’
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘rtracklayer’, ‘Rsamtools’ are not available for package ‘BSgenome’
* removing ‘/home/mikka/R/x86_64-pc-linux-gnu-library/3.6/BSgenome’

The downloaded source packages are in
	‘/tmp/RtmpEFa6gM/downloaded_packages’
Installation path not writeable, unable to update packages: mgcv, survival
Warning messages:
1: In install.packages(...) :
  installation of package ‘RCurl’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘XML’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘Rhtslib’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘GenomeInfoDb’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘GenomicRanges’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘SummarizedExperiment’ had non-zero exit status
7: In install.packages(...) :
  installation of package ‘Rsamtools’ had non-zero exit status
8: In install.packages(...) :
  installation of package ‘GenomicAlignments’ had non-zero exit status
9: In install.packages(...) :
  installation of package ‘rtracklayer’ had non-zero exit status
10: In install.packages(...) :
  installation of package ‘BSgenome’ had non-zero exit status

**Comment by hpages** [comment]
This does not look like a BSgenome issue. As you can see, many packages couldn't be installed, not just BSgenome. The fact that BSgenome failed to install is just the consequence of other packages required (directly or indirectly) by BSgenome failing to install.

At the root of the problem, it seems that installation of CRAN packages RCurl and XML failed, thus preventing many Bioconductor packages from installing. Please consult on general purpose forums / mailing lists, or directly with the authors / maintainers of these packages for advice. As always people will ask you to provide the output of your `sessionInfo()` so they can help you.

Best,
H.

**Comment by bigguscodus** [comment]
Thank you!

**Comment by hpages** [comment]
I hope you were able to sort this out. Closing this now.

**Comment by jdblischak** [comment]
Both RCurl

```
checking for curl-config... no
Cannot find curl-config
```

and Rhtslib

```
hfile_libcurl.c:45:10: fatal error: curl/curl.h: No such file or directory
```

failed to install because the libcurl development files aren't available. This can be fixed on Debian/Ubuntu by running the following:

```
sudo apt install libcurl4-openssl-dev
```

**Comment by hpages** [comment]
Please don't post in a closed issue, especially if your post has nothing to do with BSgenome. Thx!
