### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by WangxiaowuLab** [Bioconductor/BSgenome#54]
When I forge Brassica rapa BSgenome, I got the problem
> forgeBSgenomeDataPkg("./BSgenome.Brassica.rapaV3.0-seed", verbose=TRUE)
Creating package in ./BSgenome.BRAD.BrapaV3.0 
Copying '/43t/zhanglp/hic/bowtie2_index/Brapa_sequence.2bit' to './BSgenome.BRAD.BrapaV3.0/inst/extdata/single_sequences.2bit' ... Error in .copyTwobitFile(seqfile_name, seqs_srcdir, seqs_destdir, verbose = verbose) : 
  FAILED
In addition: Warning message:
In file.create(to[okay]) :
  cannot create file './BSgenome.BRAD.BrapaV3.0/inst/extdata/single_sequences.2bit', reason 'No such file or directory'

The following is seed file:
Package: BSgenome.BRAD.BrapaV3.0
Title: Full genome sequences for Brassica rapa (BRAD version Brapa_V3.0)
Description: Full genome sequences for Brassica rapa as provided by BRAD (BrapaV3.0) and stored in Biostrings objects.
Version: 1.0.0
organism: Brapa
common_name: Brapa
genome: Brapa
provider: BRAD
release_date: Feb 2022
source_url: http://39.100.233.196:82/download_genome/Brassica_Genome_data/Brara_Chiifu_V3.0/Brapa_sequence_v3.0.fasta.gz
organism_biocview: Brapa rapa
BSgenomeObjname: Brapa
SrcDataFiles: Brapa_sequence.2bit, transferred by faToTwoBit
PkgExamples: genome$1  # same as genome[["1"]]
# directory of seed file
seqs_srcdir: /43t/zhanglp/hic/bowtie2_index
# name of seed file
seqfile_name: Brapa_sequence.2bit
circ_seqs: character(0)

Can you help me?

**Comment by vjcitn** [comment]
See https://support.bioconductor.org/p/9136141/ ... the error you are reporting seems to relate to the operating system -- you may need to look at your folder permissions or preparation of the files to be written.

**Comment by hpages** [comment]
@zhanglp996 What system are you on? Can you please provide the output of your `sessionInfo()`? Note that the process of forging a BSgenome data package is only supported on Linux at the moment, as mentioned in the "How to forge a BSgenome data package" vignette.

Also it's better to ask this type of question on the Bioconductor support site at https://support.bioconductor.org/ (please make sure to read the Posting Guide before you post there). GitHub issues are preferably for reporting bugs.

Finally, note that opening an issue or starting a conversation with the title "Help" is not good practice. Please use a more descriptive title in the future. Thanks!

**Comment by WangxiaowuLab** [comment]
Thank you very much!
I have solved the problem by changing another linux platform




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bioconductor/BSgenome"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月24日(星期四) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bioconductor/BSgenome] Help (Issue #54)





 
@zhanglp996 What system are you on? Can you please provide the output of your sessionInfo()? Note that the process of forging a BSgenome data package is only supported on Linux at the moment, as mentioned in the "How to forge a BSgenome data package" vignette.
 
Also it's better to ask this type of question on the Bioconductor support site at https://support.bioconductor.org/ (please make sure to read the Posting Guide before you post there). GitHub issues are preferably for reporting bugs.
 
Finally, note that opening an issue or starting a conversation with the title "Help" is not good practice. Please use a more descriptive title in the future. Thanks!

**Comment by WANGchuang715** [comment]
> Thank you very much! I have solved the problem by changing another linux platform
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Bioconductor/BSgenome" ***@***.***&gt;; 发送时间:&nbsp;2022年11月24日(星期四) 中午11:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Bioconductor/BSgenome] Help (Issue #54) @zhanglp996 What system are you on? Can you please provide the output of your sessionInfo()? Note that the process of forging a BSgenome data package is only supported on Linux at the moment, as mentioned in the "How to forge a BSgenome data package" vignette. Also it's better to ask this type of question on the Bioconductor support site at https://support.bioconductor.org/ (please make sure to read the Posting Guide before you post there). GitHub issues are preferably for reporting bugs. Finally, note that opening an issue or starting a conversation with the title "Help" is not good practice. Please use a more descriptive title in the future. Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

I have the same problem on the centos system, may I ask which linux platform you are on without reporting an error？
