### ISSUE TITLE
add new version of genome

### ISSUE THREAD

**Issue by AndressaOL** [Bioconductor/BSgenome#58]
Hi,
I hope you are doing well. 
I am looking for the new version of the chicken genome, but it has yet to be available (available.genomes()).
Could you please add the new version of the chicken genome (GRCg7b) as BS.genome data?  NCBI or Ensembl. 
https://www.ensembl.org/Gallus_gallus/Info/Index
https://www.ncbi.nlm.nih.gov/genome/?term=chicken
Thanks

**Comment by hpages** [comment]
Hi, please take a look at issue #26 and let us know if you still have questions. Thanks

**Comment by hpages** [comment]
No news == good news, I guess
