### ISSUE TITLE
Add New Genome!

### ISSUE THREAD

**Issue by hyBio** [Bioconductor/BSgenome#6]
Hi,
Can you add this genome file to your DB?And we will library it conveniently!
UCSC Genome Browser assembly ID: bosTau9
Thanks.

**Comment by hpages** [comment]
Please see https://support.bioconductor.org/p/126958/ for new BSgenome data packages announced recently (including bosTau9).

**Comment by hyBio** [comment]
> Please see https://support.bioconductor.org/p/126958/ for new BSgenome data packages announced recently (including bosTau9).

Thanks so much for your nice work!
