### ISSUE TITLE
`BSgenome` to failing on Bioc release and devel

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/BSgenome#60]
Hi @hpages 

Just wanted to give you a quick heads up, `BSgenome` seems to failing on Bioc release and devel. You may already know this but wanted to let you know here in case the automated email doesn't get sent right away.

https://bioconductor.org/packages/release/bioc/html/BSgenome.html
https://bioconductor.org/packages/devel/bioc/html/BSgenome.html

Or if you've already addressed this and it's just a matter of waiting for the Bioc builds to update, feel free to close this out!

Best, 
Brian

**Comment by hpages** [comment]
Hi Brian,

Yes I saw that. I committed a fix yesterday night (commit 58f088e7fd331f61379bcd21c3bedd51e18b438a). The error should disappear from the daily report in the next couple of days:

- https://bioconductor.org/checkResults/3.16/bioc-LATEST/BSgenome/
- https://bioconductor.org/checkResults/3.17/bioc-LATEST/BSgenome/

Thanks,
H.

**Comment by bschilder** [comment]
Ok great, thanks so much for being so on top of this!
