### ISSUE TITLE
Conflict with rtracklayer 

### ISSUE THREAD

**Issue by AlohaPropolis** [Bioconductor/BSgenome#61]
Install rtracklayer separate from BSgenome using the following method instead of loading it from BSgenome.

> library(devtools)
> library(roxygen2)

Create directory RTRACKLAYER
move to that directory and run 

> create_package(“rtracklayer”) 

This will create the directory called rtracklayer with one file and an empty R directory. Replace all of the contents of this directory with the files and directories in the rtracklayer found in the GitHub repository. Now from the RTRACKLAYER directory run 

> document(rtracklayer)

This will rebuild the folder with the correct “namespace”.
Load the new package 
> library(rtracklayer)

Then install the “new coded”BSgenome package which does not attempts to load rtracklayer.

**Comment by hpages** [comment]
Doesn't work for me:
```
> document('rtracklayer')
ℹ Updating rtracklayer documentation
ℹ Loading rtracklayer
Creating a generic function for ‘offset’ from package ‘stats’ in package ‘rtracklayer’
Warning messages:
1: roxygen2 requires Encoding: "UTF-8"
ℹ Current encoding is NA 
2: Skipping NAMESPACE
✖ It already exists and was not generated by roxygen2. 
```

Also I don't know what the “new coded”BSgenome package is.

Also I don't understand the purpose of all the acrobatics with creating RTRACKLAYER, running `create_package(“rtracklayer”)` in it, replacing all of the contents of that with the files and directories etc.. etc.. when you can simply run `document()`  from within a `git clone` of the **rtracklayer** package. Am I missing something?

**Comment by hpages** [comment]
No answer. I guess all is good then. Shall we close this?
