### ISSUE TITLE
Forge BSgenome data package for NCBI assembly bStrHab1.2.pri

### ISSUE THREAD

**Issue by kakopo** [Bioconductor/BSgenome#63]
Create BSgenome data package for NCBI assembly bStrHab1.2.pri.
_More to be added._

**Comment by hpages** [comment]
Thanks for helping the cause of the poor endangered kākāpō bird! :wink: 

I would suggest that you open an issue to _register_ this assembly in **GenomeInfoDb**. Once it's registered, it will be quite easy for anybody to forge the corresponding BSgenome data package, if they need it, and even more so with the new `forgeBSgenomeDataPkgFromNCBI()` function that you are working on. So we won't really need to create this package ourselves and/or add it to Bioconductor (note that we normally do this for UCSC genomes, regardless of demand, but for NCBI assemblies, only if there's actually a strong demand).

H.

**Comment by kakopo** [comment]
Oh yes, definitely. Because of the work I had been doing so far I'd automatically gone straight to forging the package instead! Let me close this issue. Thank you.
