### ISSUE TITLE
Error reported when creating Masked BSgenome 

### ISSUE THREAD

**Issue by Song-10-YF** [Bioconductor/BSgenome#66]
Hi,

I'm just using BSgenome and not yet very skilled. The following error occurred when I created masked BSgenome in R.
"Error in forgeMaskedBSgenomeDataPkg(y, masks_srcdir = masks_srcdir, destdir = destdir,  : 
 values for symbols PKGVERSION are not single strings"
My seed file is as follows：
"RefPkgname: BSgenome.Psubhirtella.MengLi.ps1
source_url: 
organism_biocview: Prunus_subhirtella
nmask_per_seq: 2
SrcDataFiles: AGAPS masks:F:\NFU\P_subhirtella_genome\Psub_V1.0.mask.agp
				RM masks: F:\NFU\P_subhirtella_genome\Psub.mask.fa.out
masks_srcdir: F:\NFU\P_subhirtella_genome\mask"

Looking forward to your response.

Best,
Yanfeng

**Comment by hpages** [comment]
Your seed file looks so incomplete! It lacks plenty of mandatory fields like `Package`, `Title`, `Description`, `Version`, `Author`, etc...

Please refer to the "How to forge a BSgenome data package" vignette in the **BSgenome** package for how to prepare a seed file for a masked BSgenome data package.

Also please note that the regular BSgenome data package (**BSgenome.Psubhirtella.MengLi.ps1** in your case) is usually all what is needed as it covers 99% of the use cases. So make you sure that you really need **BSgenome.Psubhirtella.MengLi.ps1.masked** before trying to forge it.

Best,
H.

**Comment by Song-10-YF** [comment]
Hi,



This is the complete seed file (as shown below). Sorry, I just intercepted the problematic part.

Yes, my BSgenome.Psubhirtella.MengLi.ps1 has been successfully installed in R. 




Package: BSgenome.Psubhirtella.MengLi.ps1.masked
Title: Full masked genome sequences for Prunus subhirtella
Description: Full masked genome sequences for Prunus subhirtella (Higan cherry) as provided by MengLi (PS1, July. 2022) and stored in Biostrings objects.
RefPkgname: BSgenome.Psubhirtella.MengLi.ps1
source_url: 
organism_biocview: Prunus_subhirtella
nmask_per_seq: 2
SrcDataFiles: AGAPS masks:F:\NFU\P_subhirtella_genome\Psub_V1.0.mask.agp
&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; RM masks: F:\NFU\P_subhirtella_genome\Psub.mask.fa.out
masks_srcdir: F:\NFU\P_subhirtella_genome\mask



Best,
Yanfeng

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bioconductor/BSgenome"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 中午1:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bioconductor/BSgenome] Error reported when creating Masked BSgenome  (Issue #66)





 
Your seed file looks so incomplete! It lacks plenty of mandatory fields like Package, Title, Description, Version, Author, etc...
 
Please refer to the "How to forge a BSgenome data package" in the BSgenome package for how to prepare a seed file for a masked BSgenome data package.
 
Also please note that the regular BSgenome data package (BSgenome.Psubhirtella.MengLi.ps1 in your case) is usually all what is needed as it covers 99% of the use cases. So make you sure that you really need BSgenome.Psubhirtella.MengLi.ps1.masked before trying to forge it.
 
Best,
 H.

**Comment by hpages** [comment]
Sorry but I still don't see the `Version` field in your seed file!

Again, please take the time to read carefully the "How to forge a BSgenome data package" vignette in the **BSgenome** package for how to prepare a seed file for a masked BSgenome data package.

**Comment by Song-10-YF** [comment]
Hi,
I still encounter the following reported error：


In the masks_srcdir: ./mask directory, I put only masked genome files in fasta format, and I also prepared .2bit format files with the same name, as follows:

Also, I have also converted the masked genome to .agp and provided the RM .out file.
Looking forward to your reply, thank you!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Bioconductor/BSgenome"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 凌晨3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bioconductor/BSgenome] Error reported when creating Masked BSgenome  (Issue #66)





 
Sorry but I still don't see the Version field in your seed file!
 
Again, please take the time to read carefully the "How to forge a BSgenome data package" vignette in the BSgenome package for how to prepare a seed file for a masked BSgenome data package.

**Comment by hpages** [comment]
> In the masks_srcdir: ./mask directory, I put only masked genome files in fasta format, and I also prepared .2bit format files with the same name, as follows:

Note that "as follows:" is not followed by anything in your post above.

Anyways that's not what we put in the `masks/` folder. Please refer to the "How to forge a BSgenome data package" vignette for what to put there.

**Comment by hpages** [comment]
@Song-10-YF Were you able to sort this out? Is it ok to close the issue? Thanks
