### ISSUE TITLE
Error Forging BSGenome

### ISSUE THREAD

**Issue by woodjosh7** [Bioconductor/BSgenome#68]
Hello, 

I have examined the manual and other issues and can't seem to figure out what is going wrong with my attempts to forge a BSgenome for a novel genome outside of NCBI and UCSC. I do not receive an error when running the forge command, but it finishes immediately and results in no tarball for me to build to finish the process. 

Command:
`forgeBSgenomeDataPkg("~/Documents/Tuber_Evolution/dm_genome_files/BSgenome.Stuberosum.BUELL.DMv6.1-seed")`

Output: 
```
Creating package in ./BSgenome.Stuberosum.BUELL.DMv6.1 
Copying '/Users/woodjos/Documents/Tuber_Evolution/dm_genome_files/DM_1-3_516_R44_potato_genome_assembly.v6.1.2bit' to './BSgenome.Stuberosum.BUELL.DMv6.1/inst/extdata/single_sequences.2bit' ... DONE
```

Here is my seed file: 

```
Package: BSgenome.Stuberosum.BUELL.DMv6.1
Title: Full genome sequences for Solanum tuberosum, DM v6.1
Description: Full genome sequences for Solanum tuberosum, DM v6.1
Version: v6.1
organism: Solanum tuberosum, DM
common_name: DM
genome: Soltu_DMv6.1
provider: BUELL
release_date: Sep. 2020
source_url: http://spuddb.uga.edu/data/
organism_biocview: Soltu_DMv6.1
BSgenomeObjname: dmv6.1
circ_seqs: character(0)
SrcDataFiles: http://spuddb.uga.edu/data/DM_1-3_516_R44_potato_genome_assembly.v6.1.fa.gz
seqs_srcdir: /Users/woodjos/Documents/Tuber_Evolution/dm_genome_files
seqfile_name: DM_1-3_516_R44_potato_genome_assembly.v6.1.2bit
```
Here is the output directory and contents from the above command: 

```
BSgenome.Stuberosum.BUELL.DMv6.1
├── DESCRIPTION
├── NAMESPACE
├── R
│   └── zzz.R
├── inst
│   └── extdata
│       └── single_sequences.2bit
└── man
    └── package.Rd

4 directories, 5 files
```

Is there an error in my seed file or is there something else I am missing?

**Comment by hpages** [comment]
I don't see any problem. The package seems to have been succesfully created. To produce the source tarball, run `R CMD build` on the package source tree. AFAIK all this is explained in the "How to forge a BSgenome data package" vignette.

**Comment by hpages** [comment]
Closing this now
