### ISSUE TITLE
Please help adding Xenopus tropicalis to GenomeInfoDb package

### ISSUE THREAD

**Issue by clarkzor** [Bioconductor/BSgenome#75]
Hello, I am trying to utilize the "forgeBSgenomeDataPkg("../Xenopustropicalis_Seedfile.dcf")" to create a new package from a seed file, however I receive the error message:

Error in .make_Seqinfo_from_genome(genome) : 
  "xenTro" is not a registered NCBI assembly or UCSC genome (use registered_NCBI_assemblies() or
  registered_UCSC_genomes() to list the NCBI or UCSC assemblies/genomes currently registered in the
  GenomeInfoDb package)

This is what my seed file looks like:

Package: BSgenome.Xtrop.NCBI.UCB_Xtro_10.0
Title: Full genomic sequences for Xenopus Tropicalis VIA NCBI
Description: For Multiomic Analysis
Version: 1.0.0
organism: Xenopus tropicalis
common_name: Frog
provider: NCBI
genome: UCB_Xtro_10.0
release_date: Nov. 2019
source_url: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000004195.4/
organism_biocview: Xenopus_tropicalis
BSgenomeObjname: Xtrop
seqs_srcdir: /Users/coron/OneDrive/Desktop/10xGenomics/
seqfile_name: UCB_Xtro_10.0_genome.fasta

could you please add the Xenopus tropicalis genome to the GenomeInfoDb package so that I could use this function. 

Also, should I be able to run this using a single genomic fasta file that contains information about all the chromosomes, or do I have to actually split up the chromosomes into their own individual fasta files?

Thank you for your help.

**Comment by hpages** [comment]
The seed file approach has been superseded by the `forgeBSgenomeDataPkgFromNCBI()` and `forgeBSgenomeDataPkgFromUCSC()` functions from the new **BSgenomeForge** package:
```
library(BSgenomeForge)
forgeBSgenomeDataPkgFromNCBI("GCF_000004195.4", pkg_maintainer="Your Name <your.email@address.com>")
```
This will create the **BSgenome.Xtropicalis.NCBI.UCBXtro10.0** package in the current directory.

Best,
H.

**Comment by hpages** [comment]
Were you able to create the **BSgenome.Xtropicalis.NCBI.UCBXtro10.0** package @clarkzor?
